[[redirects]]
  from = "/netlify-ssl"
  to = "/2021/03/using-custom-ssl-certificate-with-netlify"

[[redirects]]
  from = "/using-custom-ssl-certificate-with-netlify"
  to = "/2021/03/using-custom-ssl-certificate-with-netlify"

[[redirects]]
  from = "/factory-arrow-functions-in-ts"
  to = "/2020/09/factory-arrow-functions-in-ts"

[[redirects]]
  from = "/factory-arrow-functions-in-js"
  to = "/2020/09/factory-arrow-functions-in-js"

[[redirects]]
  from = "/functional-vs-non-functional-requirements"
  to = "/2020/07/functional-vs-non-functional-requirements"

[[redirects]]
  from = "/meeting-notes"
  to = "/2020/06/meeting-notes"